### PR TITLE
MPIT-107 - Select github branch from notebooks

### PR DESCRIPTION
**Pull request by Kyle-Chelliah**

### CODE REVIEW

**Comment by lauravignoli** [comment]
@Kyle-Chelliah Please add the jira code at the beginning of the ticket in future. This is so that we can track down the changes in case we need to understand something in future. You can add a commit title and description. For example:

MPIT-107 Select github branch from notebooks
Added a drop down with branch options to pull the correct version for the python scripts from the notebook.

**Comment by lauravignoli** [comment]
@Kyle-Chelliah Can you please add this code to the other 2 notebooks as well?

**Comment by lauravignoli** [comment]
@Kyle-Chelliah I got this error when I ran the notebook: 
error 107

**Comment by lauravignoli** [comment]
@Kyle-Chelliah When writing commit messages please try to do think that the repository has many different sections and content. When saying "Added "select github branch" code", for example, it would be clearer if it said "Added "select github branch" code to Blocking notebook"

Just something to consider. 

Also, please remember to add the Jira ticket at the beginning of the commit message.

MPIT-107 Added "select github branch" code to Blocking notebook

**Comment by Kyle-Chelliah** [comment]
> @Kyle-Chelliah I think this commit has more than just the required changes. Can you please check?

From my side, all changes in this commit is relevant. I had to change the code from "cloning the entire repo" to "only selecting the required files from the relevant branch" in which this effected quite a number of code cells in the notebook.

**Pull request merged**
